#!/usr/bin/expect

set timeout 1

for {set i 1} {$i < $argc} {incr i} {
    set sPath [lindex $argv $i]
    puts "\n"
    spawn scp -r $sPath developer@192.168.100.100:/data/developer/
    expect {
    "yes/no" { send "yes\r"; exp_continue}
    "password:" { send "system\r" }
    "Password:" { send "system\r" }
    }
}

interact
