#!/usr/bin/expect

set timeout 1

#spawn ssh-keygen -f "/home/zmm/.ssh/known_hosts" -R 192.168.100.100

spawn ssh 192.168.100.100 -l developer

expect {
"yes/no" { send "yes\r"; exp_continue}
"password:" { send "system\r" }
"Password:" { send "system\r" }
}

expect "~$*"

send  "su root\r"

expect {
    "password:" {send "system\r"}
    "Password:" {send "system\r"}
}

send "mount -o remount, rw / \r"

interact
