#!/usr/bin/expect

set fastboot "fastboot"
set qfile "9008"
set screen "screen"

for {set i 0} {$i < $argc} {incr i} {
    set key [lindex $argv $i]
    append cmd " "
    append cmd $key
}

puts ">>>>>>>>>> $cmd <<<<<<<<<<"
set timeout 300
set loop 1

spawn adb wait-for-device
expect {
    "?C" {exit 0}
}

spawn adb root
expect {
    "restarting" { sleep 1 }
}

while {$loop} {
    spawn adb shell
    expect {
        "#" {set loop 0}
        "?C" {exit 0}
        "error:" {sleep 1}
    }
}

send "telnet cdc-qnx\r";
expect {
    "error:" {exit 0}
    "#" {
            send "telnet cdc-qnx\r";
            exp_continue
        }
    "unreachable" { sleep 2; exp_continue}

    "login:" {send "root\r"}
}

expect "Logging" {
    sleep 1
    if {[string compare $cmd $fastboot] == 0} {
        send "reset -f\r"
    } elseif {[string compare $cmd $qfile] == 0} {
        send "enter_9008_mode.sh\r"
    } elseif {[string compare $cmd $screen] == 0} {
        send "megapm_switch_state.sh \r"
    } else {
        send "$cmd\r"
    }
}

interact
