#! /bin/bash
if [ $# = 0 ]; then 
    qshell
elif [ $1 = "pull" ]; then
    qpull $@
elif [ $1 = "push" ]; then
    qpush $@
elif [ $1 = "log" ]; then
    qlog $@
elif [ $1 = "-h" ]; then
    echo "qdb tool is base on adb and telnet tools, auto run adb and telnet cmds."
    echo "use qdb [args]"
    echo "args:"
    echo "  []: enter qnx system and interact"
    echo ""
    echo "  [9008]: 8155 enter 9008 mode"
    echo ""
    echo "  [fastboot]: 8155 enter fastboot mode"
    echo ""
    echo "  [mreset]: mcu reset 8155"
    echo ""
    echo "  [log] <keywords>: enter qnx system and run \"slog2info -b keywords -w\""
    echo "      example: qdb log qvm test"
    echo "              enter qnx system and run \"slog2info -b qvm -b test -w\""
    echo ""
    echo "  [push] <files/folder> <path>: push <files/folder> to qnx system <path>"
    echo "      example: qdb push ./test1 ./test2 /data"
    echo "              push ./test1 ./test2 from your ubuntu system to qnx system."
    echo ""
    echo "  [pull] <file/folder> <path>: pull <files/folder> from qnx system to your ubuntu system <path>"
    echo "      example: qdb pull /data/test1 ./"
    echo "              pull /data/test1 from qnx system to your ubuntu ./"
    echo ""
    echo "  other cmds: enter qnx system and run cmd + args"
    echo "      example: qdb ls -la"
    echo "              enter qnx system and run ls -la"
    echo "      example: qdb reset"
    echo "              enter qnx system and run reset"
    echo "      example: qdb reset -f"
    echo "              enter qnx system and run reset -f"
else
    qcmd $@
fi
