#!/usr/bin/expect

set cmd "slog2info"

for {set i 1} {$i < $argc} {incr i} {
    set key [lindex $argv $i]
    append cmd " -b "
    append cmd $key
}

append cmd " -w"

set timeout 300
set loop 1

spawn adb wait-for-device
expect {
    "?C" {exit 0}
}

spawn adb root
expect {
    "restarting" { sleep 1 }
}

while {$loop} {
    spawn adb shell
    expect {
        "#" {set loop 0}
        "?C" {exit 0}
        "error:" {sleep 1}
    }
}

send "telnet cdc-qnx\r";
expect {
    "error:" {exit 0}
    "#" {
            send "telnet cdc-qnx\r";
            exp_continue
        }
    "unreachable" { sleep 2; exp_continue}

    "login:" {send "root\r"}
}

expect "Logging" {send "$cmd\r"}

interact
