#!/usr/bin/expect

set cmd "slog2info"

for {set i 1} {$i < $argc} {incr i} {
    set key [lindex $argv $i]
    append cmd " -b "
    append cmd $key
}

append cmd " -w"

set timeout 300

spawn adb wait-for-device
expect {
"?C" {exit 0}
}

spawn adb root
spawn adb shell

expect {
"error:" {exit 0}
"?C" { exit 0}
"#" { 
        send "telnet cdc-qnx\r";
        exp_continue
    }

"login:" {send "root\r"; exp_continue}
"Logging" {send "$cmd\r"}
}

interact
