#!/usr/bin/expect


set qpath [lindex $argv 1]
set tpath [lindex $argv 2]
set f [file tail $qpath]
set timeout 300

spawn adb wait-for-device
expect {
"?C" {exit 0}
}

spawn adb root
spawn adb shell

expect {
"error:" {exit 0}
"?C" { exit 0}
"#" { 
        send "telnet cdc-qnx\r";
        exp_continue
    }

"login:" {send "root\r"}
}

set timeout 3000

expect "Logging"
send "cp -r $qpath /ota/android/\r"

expect "#"
send "exit\r"

expect "?:/ #"
send "cp -r /ota/$f /data\r"

expect "?:/ #"
send "exit\r"

expect "?$"
spawn adb pull /data/$f $tpath

expect eof
