#!/usr/bin/expect


set qpath [lindex $argv 1]
set tpath [lindex $argv 2]
set f [file tail $qpath]
set timeout 300
set loop 1

spawn adb wait-for-device
expect {
    "?C" {exit 0}
}

spawn adb root
expect {
    "restarting" { sleep 1 }
}

while {$loop} {
    spawn adb shell
    expect {
        "#" {set loop 0}
        "?C" {exit 0}
        "error:" {sleep 1}
    }
}

send "telnet cdc-qnx\r";
expect {
    "error:" {exit 0}
    "#" { 
            send "telnet cdc-qnx\r";
            exp_continue
        }
    "unreachable" { sleep 2; exp_continue}

    "login:" {send "root\r"}
}

set timeout 3000

expect "Logging"
send "cp -r $qpath /ota/android/\r"

expect "#"
send "exit\r"

expect "?:/ #"
send "cp -r /ota/$f /data\r"

expect "?:/ #"
send "exit\r"

expect "?$"
spawn adb pull /data/$f $tpath

expect eof
